[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
